#!/bin/bash

# Clear the terminal screen
clear

# Get current user
USER=$(whoami)

# Get current date in a human-readable format
CURRENT_DATE=$(date "+%A, %B %d, %Y at %T")

# Get system hostname
SYSTEM_HOSTNAME=$(hostname)

# Get operating system information
OS_INFO=$(cat /etc/os-release | grep "PRETTY_NAME" | cut -d '=' -f2 | tr -d '"')

# Get system uptime
UPTIME=$(uptime -p)

# Get CPU model
CPU_MODEL=$(lscpu | grep 'Model name' | awk -F': ' '{print $2}' | sed 's/^ *//')

# Get total RAM installed
RAM_SIZE=$(grep MemTotal /proc/meminfo | awk '{print $2/1024 " MB"}')

# Get disk information (device, size, and model)
DISK_INFO=$(lsblk -d -o NAME,SIZE,MODEL | tail -n +2 | sort -r)

# Get video card model
VIDEO_CARD=$(lspci | grep -i vga | awk -F: '{print $3}' | sed 's/^ //')

# Get Fully Qualified Domain Name (FQDN)
FQDN=$(hostname -f)

# Get IP address of the default gateway interface
IP_ADDRESS=$(ip -4 addr show | grep inet | grep -v '127.0.0.1' | awk '{print $2}' | head -n 1)

# Get default gateway IP
GATEWAY=$(ip route show default | awk '{print $3}')

# Get DNS server IP
DNS_IP=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n 1)

# Get list of logged-in users
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)

# Get disk space usage (for all mounted file systems)
DISK_USAGE=$(df -h | awk '/^\/dev/ {print $6 ": " $4 " free"}')

# Get the number of processes running
PROCESS_COUNT=$(ps -e | wc -l)

# Get system load averages
LOAD_AVERAGE=$(uptime | awk -F'load average:' '{print $2}' | sed 's/,/ /g')

# Get listening network ports
LISTENING_PORTS=$(ss -tuln | awk '/LISTEN/ {print $5}' | cut -d':' -f2 | sort -n | uniq | paste -sd "," -)

# Get UFW firewall status
FIREWALL_STATUS=$(sudo ufw status | grep "Status" | awk '{print $2}')

# Print the system information in a readable format
cat << EOF

System Report generated by $USER, $CURRENT_DATE

System Information
------------------
Hostname: $SYSTEM_HOSTNAME
OS: $OS_INFO
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU_MODEL
RAM: $RAM_SIZE
Disk(s): 
$DISK_INFO
Video: $VIDEO_CARD

Network Information
-------------------
FQDN: $FQDN
Host Address: $IP_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_IP

System Status
-------------
Users Logged In: $LOGGED_IN_USERS
Disk Space: 
$DISK_USAGE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGE
Listening Network Ports: $LISTENING_PORTS
Firewall Status: $FIREWALL_STATUS

EOF
