#!/bin/bash

# System Information
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo $PRETTY_NAME)
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(lscpu | grep "Model name" | awk -F: '{print $2}' | xargs)
RAM=$(free -h | awk '/^Mem:/ {print $2}')
DISKS=$(lsblk -d -o MODEL,SIZE | grep -v "MODEL")
VIDEO=$(lspci | grep VGA | cut -d ":" -f3 | xargs)

# Network Information
FQDN=$(hostname --fqdn)
HOST_IP=$(ip route get 1 | awk '{print $7}')
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')
DNS_SERVER=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}')

# System Status
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | paste -s -d ',')
DISK_SPACE=$(df -h / | grep '/$' | awk '{print $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVG=$(uptime | awk -F 'load average:' '{print $2}' | xargs)
LISTENING_PORTS=$(ss -tuln | awk 'NR > 1 {print $5}' | cut -d':' -f2 | sort -n | uniq | paste -s -d ',')
UFW_STATUS=$(sudo ufw status 2>/dev/null | grep "Status:" | awk '{print $2}')

# Report Header
cat <<EOF

System Report generated by $USER, $(date)

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Ram: $RAM
Disk(s):
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $LOGGED_IN_USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF

